// scripts/stores.config.js — shared store configs and disc catalog
// Used by standalone per-store scrapers
//
// NOTE: extractVariant and isUsedDisc are exported from THIS file.
// All scrapers must import from './stores.config.js', NOT './plastic-types.js'
'use strict';

const { PLASTIC_TYPES, PLAYER_NAMES, EDITION_KEYWORDS, parseProductName, isUsedDisc, isMiniDisc, isNonDiscProduct } = require('./plastic-types.js');

// ── Disc catalog (mirrors data/discs.js — keep in sync) ─────────────────────
const DISC_CATALOG = [
  { id: 'innova-destroyer', name: 'Destroyer', brand: 'Innova' },
  { id: 'discraft-buzzz', name: 'Buzzz', brand: 'Discraft' },
  { id: 'axiom-bokeh-lizotte', name: 'Neutron Bokeh', brand: 'Axiom' },
  { id: 'discmania-pd2', name: 'PD2', brand: 'Discmania' },
  { id: 'kastaplast-berg', name: 'Berg', brand: 'Kastaplast' },
  { id: 'mvp-atom', name: 'Atom', brand: 'MVP' },
  { id: 'latitude-flow', name: 'Flow', brand: 'Latitude 64' },
  { id: 'innova-aviar', name: 'Aviar', brand: 'Innova' },
  { id: 'dynamic-trespass', name: 'Trespass', brand: 'Dynamic Discs' },
  { id: 'prodigy-pa3-lizotte', name: 'PA-3 (Lizotte Edition)', brand: 'Prodigy' },
  { id: 'discmania-cloudbreaker', name: 'Cloud Breaker', brand: 'Discmania' },
  { id: 'innova-leopard', name: 'Leopard', brand: 'Innova' },
  { id: 'innova-roc', name: 'Roc', brand: 'Innova' },
  { id: 'innova-wraith', name: 'Wraith', brand: 'Innova' },
  { id: 'innova-sidewinder', name: 'Sidewinder', brand: 'Innova' },
  { id: 'dynamic-escape', name: 'Escape', brand: 'Dynamic Discs' },
  { id: 'discraft-zone', name: 'Zone', brand: 'Discraft' },
  { id: 'innova-boss', name: 'Boss', brand: 'Innova' },
  { id: 'innova-corvette', name: 'Corvette', brand: 'Innova' },
  { id: 'innova-daedalus', name: 'Daedalus', brand: 'Innova' },
  { id: 'innova-firebird', name: 'Firebird', brand: 'Innova' },
  { id: 'innova-gazelle', name: 'Gazelle', brand: 'Innova' },
  { id: 'innova-jay', name: 'Jay', brand: 'Innova' },
  { id: 'innova-katana', name: 'Katana', brand: 'Innova' },
  { id: 'innova-leopard3', name: 'Leopard3', brand: 'Innova' },
  { id: 'innova-liger', name: 'Liger', brand: 'Innova' },
  { id: 'innova-lion', name: 'Lion', brand: 'Innova' },
  { id: 'innova-mako3', name: 'Mako3', brand: 'Innova' },
  { id: 'innova-nova', name: 'Nova', brand: 'Innova' },
  { id: 'innova-orc', name: 'Orc', brand: 'Innova' },
  { id: 'innova-pig', name: 'Pig', brand: 'Innova' },
  { id: 'innova-rancho', name: 'Rancho', brand: 'Innova' },
  { id: 'innova-rhyno', name: 'Rhyno', brand: 'Innova' },
  { id: 'innova-roc3', name: 'Roc3', brand: 'Innova' },
  { id: 'innova-shryke', name: 'Shryke', brand: 'Innova' },
  { id: 'innova-stingray', name: 'Stingray', brand: 'Innova' },
  { id: 'innova-teedevil', name: 'TeeDevil', brand: 'Innova' },
  { id: 'innova-teebird', name: 'Teebird', brand: 'Innova' },
  { id: 'innova-teebird3', name: 'Teebird3', brand: 'Innova' },
  { id: 'innova-tern', name: 'Tern', brand: 'Innova' },
  { id: 'innova-thunderbird', name: 'Thunderbird', brand: 'Innova' },
  { id: 'innova-valkyrie', name: 'Valkyrie', brand: 'Innova' },
  { id: 'innova-viking', name: 'Viking', brand: 'Innova' },
  { id: 'innova-vroc', name: 'Vroc', brand: 'Innova' },
  { id: 'innova-wolf', name: 'Wolf', brand: 'Innova' },
  { id: 'innova-xt-nova', name: 'XT Nova', brand: 'Innova' },
  { id: 'discraft-anax', name: 'Anax', brand: 'Discraft' },
  { id: 'discraft-banger-gt', name: 'Banger GT', brand: 'Discraft' },
  { id: 'discraft-buzzz-gt', name: 'Buzzz GT', brand: 'Discraft' },
  { id: 'discraft-buzzz-os', name: 'Buzzz OS', brand: 'Discraft' },
  { id: 'discraft-comet', name: 'Comet', brand: 'Discraft' },
  { id: 'discraft-crank', name: 'Crank', brand: 'Discraft' },
  { id: 'discraft-crush', name: 'Crush', brand: 'Discraft' },
  { id: 'discraft-cyclone', name: 'Cyclone', brand: 'Discraft' },
  { id: 'discraft-drone', name: 'Drone', brand: 'Discraft' },
  { id: 'discraft-enigma', name: 'Enigma', brand: 'Discraft' },
  { id: 'discraft-flick', name: 'Flick', brand: 'Discraft' },
  { id: 'discraft-force', name: 'Force', brand: 'Discraft' },
  { id: 'discraft-ghost', name: 'Ghost', brand: 'Discraft' },
  { id: 'discraft-hornet', name: 'Hornet', brand: 'Discraft' },
  { id: 'discraft-luna', name: 'Luna', brand: 'Discraft' },
  { id: 'discraft-malta', name: 'Malta', brand: 'Discraft' },
  { id: 'discraft-mantis', name: 'Mantis', brand: 'Discraft' },
  { id: 'discraft-nuke', name: 'Nuke', brand: 'Discraft' },
  { id: 'discraft-nuke-os', name: 'Nuke OS', brand: 'Discraft' },
  { id: 'discraft-predator', name: 'Predator', brand: 'Discraft' },
  { id: 'discraft-captains-raptor', name: "Captain's Raptor", brand: 'Discraft' },
  { id: 'discraft-captains-raptor', name: 'Captains Raptor', brand: 'Discraft' },
  { id: 'discraft-raptor', name: 'Raptor', brand: 'Discraft' },
  { id: 'discraft-roach', name: 'Roach', brand: 'Discraft' },
  { id: 'discraft-scorch', name: 'Scorch', brand: 'Discraft' },
  { id: 'discraft-sol', name: 'Sol', brand: 'Discraft' },
  { id: 'discraft-stalker', name: 'Stalker', brand: 'Discraft' },
  { id: 'discraft-static', name: 'Static', brand: 'Discraft' },
  { id: 'discraft-stratus', name: 'Stratus', brand: 'Discraft' },
  { id: 'discraft-surge', name: 'Surge', brand: 'Discraft' },
  { id: 'discraft-thrasher', name: 'Thrasher', brand: 'Discraft' },
  { id: 'discraft-undertaker', name: 'Undertaker', brand: 'Discraft' },
  { id: 'discraft-viper', name: 'Viper', brand: 'Discraft' },
  { id: 'discraft-wasp', name: 'Wasp', brand: 'Discraft' },
  { id: 'discraft-zone-os',   name: 'Zone OS',   brand: 'Discraft' },
  { id: 'discraft-zone-ss',   name: 'Zone SS',   brand: 'Discraft' },
  { id: 'discraft-buzzz-ss',  name: 'Buzzz SS',  brand: 'Discraft' },
  { id: 'discraft-nuke-ss',   name: 'Nuke SS',   brand: 'Discraft' },
  { id: 'discraft-force-ss',  name: 'Force SS',  brand: 'Discraft' },
  { id: 'discraft-fierce-ss', name: 'Fierce SS', brand: 'Discraft' },
  { id: 'dynamic-evidence', name: 'Evidence', brand: 'Dynamic Discs' },
  { id: 'dynamic-felon', name: 'Felon', brand: 'Dynamic Discs' },
  { id: 'dynamic-freedom', name: 'Freedom', brand: 'Dynamic Discs' },
  { id: 'dynamic-fugitive', name: 'Fugitive', brand: 'Dynamic Discs' },
  { id: 'dynamic-judge', name: 'Judge', brand: 'Dynamic Discs' },
  { id: 'dynamic-maverick', name: 'Maverick', brand: 'Dynamic Discs' },
  { id: 'dynamic-renegade', name: 'Renegade', brand: 'Dynamic Discs' },
  { id: 'dynamic-sheriff', name: 'Sheriff', brand: 'Dynamic Discs' },
  { id: 'dynamic-truth', name: 'Truth', brand: 'Dynamic Discs' },
  { id: 'dynamic-verdict', name: 'Verdict', brand: 'Dynamic Discs' },
  { id: 'latitude-anchor', name: 'Anchor', brand: 'Latitude 64' },
  { id: 'latitude-ballista-pro', name: 'Ballista Pro', brand: 'Latitude 64' },
  { id: 'latitude-claymore', name: 'Claymore', brand: 'Latitude 64' },
  { id: 'latitude-diamond', name: 'Diamond', brand: 'Latitude 64' },
  { id: 'latitude-explorer', name: 'Explorer', brand: 'Latitude 64' },
  { id: 'latitude-fuse', name: 'Fuse', brand: 'Latitude 64' },
  { id: 'latitude-gauntlet', name: 'Gauntlet', brand: 'Latitude 64' },
  { id: 'latitude-grace', name: 'Grace', brand: 'Latitude 64' },
  { id: 'latitude-guard', name: 'Guard', brand: 'Latitude 64' },
  { id: 'latitude-jade', name: 'Jade', brand: 'Latitude 64' },
  { id: 'latitude-keystone', name: 'Keystone', brand: 'Latitude 64' },
  { id: 'latitude-missilen', name: 'Missilen', brand: 'Latitude 64' },
  { id: 'latitude-river', name: 'River', brand: 'Latitude 64' },
  { id: 'latitude-saint', name: 'Saint', brand: 'Latitude 64' },
  { id: 'latitude-saint-pro', name: 'Saint Pro', brand: 'Latitude 64' },
  { id: 'latitude-sapphire', name: 'Sapphire', brand: 'Latitude 64' },
  { id: 'latitude-trust', name: 'Trust', brand: 'Latitude 64' },
  { id: 'latitude-volt', name: 'Volt', brand: 'Latitude 64' },
  { id: 'kastaplast-falk', name: 'Falk', brand: 'Kastaplast' },
  { id: 'kastaplast-grym', name: 'Grym', brand: 'Kastaplast' },
  { id: 'kastaplast-grym-x', name: 'Grym X', brand: 'Kastaplast' },
  { id: 'kastaplast-gote', name: 'Göte', brand: 'Kastaplast' },
  { id: 'kastaplast-lots', name: 'Lots', brand: 'Kastaplast' },
  { id: 'kastaplast-rask', name: 'Rask', brand: 'Kastaplast' },
  { id: 'kastaplast-svart', name: 'Svart', brand: 'Kastaplast' },
  { id: 'westside-harp', name: 'Harp', brand: 'Westside Discs' },
  { id: 'westside-stag', name: 'Stag', brand: 'Westside Discs' },
  { id: 'westside-swan-1', name: 'Swan 1', brand: 'Westside Discs' },
  { id: 'westside-sword', name: 'Sword', brand: 'Westside Discs' },
  { id: 'westside-tursas', name: 'Tursas', brand: 'Westside Discs' },
  { id: 'westside-warship', name: 'Warship', brand: 'Westside Discs' },
  { id: 'axiom-alias', name: 'Alias', brand: 'Axiom' },
  { id: 'axiom-crave', name: 'Crave', brand: 'Axiom' },
  { id: 'axiom-defy', name: 'Defy', brand: 'Axiom' },
  { id: 'axiom-envy', name: 'Envy', brand: 'Axiom' },
  { id: 'axiom-hex', name: 'Hex', brand: 'Axiom' },
  { id: 'axiom-insanity', name: 'Insanity', brand: 'Axiom' },
  { id: 'axiom-proxy', name: 'Proxy', brand: 'Axiom' },
  { id: 'axiom-rhythm', name: 'Rhythm', brand: 'Axiom' },
  { id: 'mvp-octane', name: 'Octane', brand: 'MVP' },
  { id: 'mvp-relay', name: 'Relay', brand: 'MVP' },
  { id: 'mvp-servo', name: 'Servo', brand: 'MVP' },
  { id: 'mvp-tesla', name: 'Tesla', brand: 'MVP' },
  { id: 'discmania-active', name: 'Active', brand: 'Discmania' },
  { id: 'discmania-cd', name: 'CD', brand: 'Discmania' },
  { id: 'discmania-cd2', name: 'CD2', brand: 'Discmania' },
  { id: 'discmania-cd3', name: 'CD3', brand: 'Discmania' },
  { id: 'discmania-dd', name: 'DD', brand: 'Discmania' },
  { id: 'discmania-dd2', name: 'DD2', brand: 'Discmania' },
  { id: 'discmania-dd3', name: 'DD3', brand: 'Discmania' },
  { id: 'discmania-fd', name: 'FD', brand: 'Discmania' },
  { id: 'discmania-fd2', name: 'FD2', brand: 'Discmania' },
  { id: 'discmania-fd3', name: 'FD3', brand: 'Discmania' },
  { id: 'discmania-md', name: 'MD', brand: 'Discmania' },
  { id: 'discmania-md2', name: 'MD2', brand: 'Discmania' },
  { id: 'discmania-md3', name: 'MD3', brand: 'Discmania' },
  { id: 'discmania-md5', name: 'MD5', brand: 'Discmania' },
  { id: 'discmania-pd', name: 'PD', brand: 'Discmania' },
  { id: 'discmania-pd3', name: 'PD3', brand: 'Discmania' },
  { id: 'discmania-p1', name: 'P1', brand: 'Discmania' },
  { id: 'discmania-p2', name: 'P2', brand: 'Discmania' },
  { id: 'discmania-p3', name: 'P3', brand: 'Discmania' },
  { id: 'discmania-tactic', name: 'Tactic', brand: 'Discmania' },
  { id: 'prodigy-a1', name: 'A1', brand: 'Prodigy' },
  { id: 'prodigy-a2', name: 'A2', brand: 'Prodigy' },
  { id: 'prodigy-a3', name: 'A3', brand: 'Prodigy' },
  { id: 'prodigy-a4', name: 'A4', brand: 'Prodigy' },
  { id: 'prodigy-d1', name: 'D1', brand: 'Prodigy' },
  { id: 'prodigy-d2', name: 'D2', brand: 'Prodigy' },
  { id: 'prodigy-d3', name: 'D3', brand: 'Prodigy' },
  { id: 'prodigy-d4', name: 'D4', brand: 'Prodigy' },
  { id: 'prodigy-f1', name: 'F1', brand: 'Prodigy' },
  { id: 'prodigy-f3', name: 'F3', brand: 'Prodigy' },
  { id: 'prodigy-f5', name: 'F5', brand: 'Prodigy' },
  { id: 'prodigy-h1', name: 'H1', brand: 'Prodigy' },
  { id: 'prodigy-h2', name: 'H2', brand: 'Prodigy' },
  { id: 'prodigy-m1', name: 'M1', brand: 'Prodigy' },
  { id: 'prodigy-m2', name: 'M2', brand: 'Prodigy' },
  { id: 'prodigy-m3', name: 'M3', brand: 'Prodigy' },
  { id: 'prodigy-m4', name: 'M4', brand: 'Prodigy' },
  { id: 'prodigy-pa1', name: 'PA-1', brand: 'Prodigy' },
  { id: 'prodigy-pa2', name: 'PA-2', brand: 'Prodigy' },
  { id: 'prodigy-pa4', name: 'PA-4', brand: 'Prodigy' },
  { id: 'axiom-fireball', name: 'Fireball', brand: 'Axiom' },
  { id: 'axiom-mayhem', name: 'Mayhem', brand: 'Axiom' },
  { id: 'axiom-panic', name: 'Panic', brand: 'Axiom' },
  { id: 'axiom-pyro', name: 'Pyro', brand: 'Axiom' },
  { id: 'axiom-tempo', name: 'Tempo', brand: 'Axiom' },
  { id: 'axiom-tenacity', name: 'Tenacity', brand: 'Axiom' },
  { id: 'axiom-time-lapse', name: 'Time-Lapse', brand: 'Axiom' },
  { id: 'discmania-apollo', name: 'Apollo', brand: 'Discmania' },
  { id: 'discmania-atlantis', name: 'Atlantis', brand: 'Discmania' },
  { id: 'discmania-cd1', name: 'CD1', brand: 'Discmania' },
  { id: 'discmania-dd1', name: 'DD1', brand: 'Discmania' },
  { id: 'discmania-essence', name: 'Essence', brand: 'Discmania' },
  { id: 'discmania-fd1', name: 'FD1', brand: 'Discmania' },
  { id: 'discmania-fenris', name: 'Fenris', brand: 'Discmania' },
  { id: 'discmania-fjord', name: 'Fjord', brand: 'Discmania' },
  { id: 'discmania-gf1', name: 'GF1', brand: 'Discmania' },
  { id: 'discmania-glacier', name: 'Glacier', brand: 'Discmania' },
  { id: 'discmania-instinct', name: 'Instinct', brand: 'Discmania' },
  { id: 'discmania-jokeri', name: 'Jokeri', brand: 'Discmania' },
  { id: 'discmania-laseri', name: 'Laseri', brand: 'Discmania' },
  { id: 'discmania-link', name: 'Link', brand: 'Discmania' },
  { id: 'discmania-logic', name: 'Logic', brand: 'Discmania' },
  { id: 'discmania-md1', name: 'MD1', brand: 'Discmania' },
  { id: 'discmania-md4', name: 'MD4', brand: 'Discmania' },
  { id: 'discmania-method', name: 'Method', brand: 'Discmania' },
  { id: 'discmania-midari', name: 'Midari', brand: 'Discmania' },
  { id: 'discmania-notion', name: 'Notion', brand: 'Discmania' },
  { id: 'discmania-origin', name: 'Origin', brand: 'Discmania' },
  { id: 'discmania-origo', name: 'Origo', brand: 'Discmania' },
  { id: 'discmania-p1x', name: 'P1X', brand: 'Discmania' },
  { id: 'discmania-p2x', name: 'P2X', brand: 'Discmania' },
  { id: 'discmania-p3x', name: 'P3X', brand: 'Discmania' },
  { id: 'discmania-rainmaker', name: 'Rainmaker', brand: 'Discmania' },
  { id: 'discmania-sparta', name: 'Sparta', brand: 'Discmania' },
  { id: 'discmania-splice', name: 'Splice', brand: 'Discmania' },
  { id: 'discmania-steady', name: 'Steady', brand: 'Discmania' },
  { id: 'discmania-td', name: 'TD', brand: 'Discmania' },
  { id: 'discmania-talisman', name: 'Talisman', brand: 'Discmania' },
  { id: 'discmania-theios', name: 'Theios', brand: 'Discmania' },
  { id: 'discmania-vanguard',   name: 'Vanguard',   brand: 'Discmania' },
  { id: 'discmania-d-model',    name: 'D Model',    brand: 'Discmania' },
  { id: 'discmania-d-model-os', name: 'D Model OS', brand: 'Discmania' },
  { id: 'discmania-d-model-s',  name: 'D Model S',  brand: 'Discmania' },
  { id: 'discmania-f-model',    name: 'F Model',    brand: 'Discmania' },
  { id: 'discmania-f-model-os', name: 'F Model OS', brand: 'Discmania' },
  { id: 'discmania-f-model-s',  name: 'F Model S',  brand: 'Discmania' },
  { id: 'discmania-m-model',    name: 'M Model',    brand: 'Discmania' },
  { id: 'discmania-m-model-os', name: 'M Model OS', brand: 'Discmania' },
  { id: 'discmania-m-model-s',  name: 'M Model S',  brand: 'Discmania' },
  { id: 'discmania-p-model',    name: 'P Model',    brand: 'Discmania' },
  { id: 'discmania-p-model-s',  name: 'P Model S',  brand: 'Discmania' },
  { id: 'discraft-ares', name: 'Ares', brand: 'Discraft' },
  { id: 'discraft-athena', name: 'Athena', brand: 'Discraft' },
  { id: 'discraft-avenger-ss', name: 'Avenger SS', brand: 'Discraft' },
  { id: 'discraft-challenger', name: 'Challenger', brand: 'Discraft' },
  { id: 'discraft-cicada', name: 'Cicada', brand: 'Discraft' },
  { id: 'discraft-cigarra', name: 'Cigarra', brand: 'Discraft' },
  { id: 'discraft-drive', name: 'Drive', brand: 'Discraft' },
  { id: 'discraft-fierce', name: 'Fierce', brand: 'Discraft' },
  { id: 'discraft-focus', name: 'Focus', brand: 'Discraft' },
  { id: 'discraft-hades', name: 'Hades', brand: 'Discraft' },
  { id: 'discraft-heat', name: 'Heat', brand: 'Discraft' },
  { id: 'discraft-joy', name: 'Joy', brand: 'Discraft' },
  { id: 'discraft-kratos', name: 'Kratos', brand: 'Discraft' },
  { id: 'discraft-machete', name: 'Machete', brand: 'Discraft' },
  { id: 'discraft-magnet', name: 'Magnet', brand: 'Discraft' },
  { id: 'discraft-malita', name: 'Malita', brand: 'Discraft' },
  { id: 'discraft-meteor', name: 'Meteor', brand: 'Discraft' },
  { id: 'discraft-passion', name: 'Passion', brand: 'Discraft' },
  { id: 'discraft-reaper', name: 'Reaper', brand: 'Discraft' },
  { id: 'discraft-ringer-gt', name: 'Ringer GT', brand: 'Discraft' },
  { id: 'discraft-sting', name: 'Sting', brand: 'Discraft' },
  { id: 'discraft-swarm', name: 'Swarm', brand: 'Discraft' },
  { id: 'discraft-venom', name: 'Venom', brand: 'Discraft' },
  { id: 'discraft-vulture', name: 'Vulture', brand: 'Discraft' },
  { id: 'discraft-xl', name: 'XL', brand: 'Discraft' },
  { id: 'discraft-zeus', name: 'Zeus', brand: 'Discraft' },
  { id: 'discraft-zombee', name: 'Zombee', brand: 'Discraft' },
  { id: 'dynamic-bounty', name: 'Bounty', brand: 'Dynamic Discs' },
  { id: 'dynamic-captain', name: 'Captain', brand: 'Dynamic Discs' },
  { id: 'dynamic-convict', name: 'Convict', brand: 'Dynamic Discs' },
  { id: 'dynamic-culprit', name: 'Culprit', brand: 'Dynamic Discs' },
  { id: 'dynamic-deputy', name: 'Deputy', brand: 'Dynamic Discs' },
  { id: 'dynamic-enforcer', name: 'Enforcer', brand: 'Dynamic Discs' },
  { id: 'dynamic-evader', name: 'Evader', brand: 'Dynamic Discs' },
  { id: 'dynamic-getaway', name: 'Getaway', brand: 'Dynamic Discs' },
  { id: 'dynamic-gladiator', name: 'Gladiator', brand: 'Dynamic Discs' },
  { id: 'dynamic-heist', name: 'Heist', brand: 'Dynamic Discs' },
  { id: 'dynamic-justice', name: 'Justice', brand: 'Dynamic Discs' },
  { id: 'dynamic-raider', name: 'Raider', brand: 'Dynamic Discs' },
  { id: 'dynamic-sergeant', name: 'Sergeant', brand: 'Dynamic Discs' },
  { id: 'dynamic-suspect', name: 'Suspect', brand: 'Dynamic Discs' },
  { id: 'dynamic-vandal', name: 'Vandal', brand: 'Dynamic Discs' },
  { id: 'dynamic-warden', name: 'Warden', brand: 'Dynamic Discs' },
  { id: 'dynamic-valor', name: 'Valor', brand: 'Dynamic Discs' },
  { id: 'dynamic-gauge', name: 'Gauge', brand: 'Dynamic Discs' },
  { id: 'dynamic-patriot', name: 'Patriot', brand: 'Dynamic Discs' },
  { id: 'dynamic-phenom', name: 'Phenom', brand: 'Dynamic Discs' },
  { id: 'dynamic-rampage', name: 'Rampage', brand: 'Dynamic Discs' },
  { id: 'dynamic-agent', name: 'Agent', brand: 'Dynamic Discs' },
  { id: 'dynamic-breakout', name: 'Breakout', brand: 'Dynamic Discs' },
  { id: 'dynamic-defender', name: 'Defender', brand: 'Dynamic Discs' },
  { id: 'dynamic-jury', name: 'Jury', brand: 'Dynamic Discs' },
  { id: 'dynamic-motive', name: 'Motive', brand: 'Dynamic Discs' },
  { id: 'infinite-alpaca', name: 'Alpaca', brand: 'Infinite Discs' },
  { id: 'infinite-anubis', name: 'Anubis', brand: 'Infinite Discs' },
  { id: 'infinite-artifact', name: 'Artifact', brand: 'Infinite Discs' },
  { id: 'infinite-aztec', name: 'Aztec', brand: 'Infinite Discs' },
  { id: 'infinite-centurion', name: 'Centurion', brand: 'Infinite Discs' },
  { id: 'infinite-chariot', name: 'Chariot', brand: 'Infinite Discs' },
  { id: 'infinite-czar', name: 'Czar', brand: 'Infinite Discs' },
  { id: 'infinite-inca', name: 'Inca', brand: 'Infinite Discs' },
  { id: 'infinite-maya', name: 'Maya', brand: 'Infinite Discs' },
  { id: 'infinite-myth', name: 'Myth', brand: 'Infinite Discs' },
  { id: 'infinite-pharaoh', name: 'Pharaoh', brand: 'Infinite Discs' },
  { id: 'infinite-ra', name: 'Ra', brand: 'Infinite Discs' },
  { id: 'infinite-scepter', name: 'Scepter', brand: 'Infinite Discs' },
  { id: 'infinite-slab', name: 'Slab', brand: 'Infinite Discs' },
  { id: 'innova-alien', name: 'Alien', brand: 'Innova' },
  { id: 'innova-animal', name: 'Animal', brand: 'Innova' },
  { id: 'innova-ape', name: 'Ape', brand: 'Innova' },
  { id: 'innova-archon', name: 'Archon', brand: 'Innova' },
  { id: 'innova-avatar', name: 'Avatar', brand: 'Innova' },
  { id: 'innova-aviar3', name: 'Aviar3', brand: 'Innova' },
  { id: 'innova-aviarx3', name: 'AviarX3', brand: 'Innova' },
  { id: 'innova-beast', name: 'Beast', brand: 'Innova' },
  { id: 'innova-bison', name: 'Bison', brand: 'Innova' },
  { id: 'innova-cro', name: 'CRO', brand: 'Innova' },
  { id: 'innova-caiman', name: 'Caiman', brand: 'Innova' },
  { id: 'innova-charger', name: 'Charger', brand: 'Innova' },
  { id: 'innova-colossus', name: 'Colossus', brand: 'Innova' },
  { id: 'innova-colt', name: 'Colt', brand: 'Innova' },
  { id: 'innova-dart', name: 'Dart', brand: 'Innova' },
  { id: 'innova-dominator', name: 'Dominator', brand: 'Innova' },
  { id: 'innova-eagle', name: 'Eagle', brand: 'Innova' },
  { id: 'innova-fl', name: 'FL', brand: 'Innova' },
  { id: 'innova-fenris', name: 'Fenris', brand: 'Innova' },
  { id: 'innova-firefly', name: 'Firefly', brand: 'Innova' },
  { id: 'innova-firestorm', name: 'Firestorm', brand: 'Innova' },
  { id: 'innova-fox', name: 'Fox', brand: 'Innova' },
  { id: 'innova-gator', name: 'Gator', brand: 'Innova' },
  { id: 'innova-gorgon', name: 'Gorgon', brand: 'Innova' },
  { id: 'innova-hawkeye', name: 'Hawkeye', brand: 'Innova' },
  { id: 'innova-it', name: 'IT', brand: 'Innova' },
  { id: 'innova-invader', name: 'Invader', brand: 'Innova' },
  { id: 'innova-invictus', name: 'Invictus', brand: 'Innova' },
  { id: 'innova-krait', name: 'Krait', brand: 'Innova' },
  { id: 'innova-mamba', name: 'Mamba', brand: 'Innova' },
  { id: 'innova-max', name: 'Max', brand: 'Innova' },
  { id: 'innova-mirage', name: 'Mirage', brand: 'Innova' },
  { id: 'innova-mystere', name: 'Mystere', brand: 'Innova' },
  { id: 'innova-panther', name: 'Panther', brand: 'Innova' },
  { id: 'innova-racer', name: 'Racer', brand: 'Innova' },
  { id: 'innova-rat', name: 'Rat', brand: 'Innova' },
  { id: 'innova-roadrunner', name: 'Roadrunner', brand: 'Innova' },
  { id: 'innova-rocx3', name: 'RocX3', brand: 'Innova' },
  { id: 'innova-rollo', name: 'Rollo', brand: 'Innova' },
  { id: 'innova-savant', name: 'Savant', brand: 'Innova' },
  { id: 'innova-shark', name: 'Shark', brand: 'Innova' },
  { id: 'innova-starfire', name: 'Starfire', brand: 'Innova' },
  { id: 'innova-tl', name: 'TL', brand: 'Innova' },
  { id: 'innova-tl3', name: 'TL3', brand: 'Innova' },
  { id: 'innova-toro', name: 'Toro', brand: 'Innova' },
  { id: 'innova-wedge', name: 'Wedge', brand: 'Innova' },
  { id: 'innova-wombat3', name: 'Wombat3', brand: 'Innova' },
  { id: 'innova-xcaliber', name: 'XCaliber', brand: 'Innova' },
  { id: 'innova-xcaliber', name: 'X-Caliber', brand: 'Innova' },
  { id: 'innova-xd', name: 'XD', brand: 'Innova' },
  { id: 'innova-rhynox', name: 'RhynoX', brand: 'Innova' },
  { id: 'innova-aero', name: 'Aero', brand: 'Innova' },
  { id: 'innova-arachnid', name: 'Arachnid', brand: 'Innova' },
  { id: 'innova-archangel', name: 'Archangel', brand: 'Innova' },
  { id: 'innova-atlas', name: 'Atlas', brand: 'Innova' },
  { id: 'innova-banshee', name: 'Banshee', brand: 'Innova' },
  { id: 'innova-birdie', name: 'Birdie', brand: 'Innova' },
  { id: 'innova-bullfrog', name: 'Bullfrog', brand: 'Innova' },
  { id: 'innova-cheetah', name: 'Cheetah', brand: 'Innova' },
  { id: 'innova-cobra', name: 'Cobra', brand: 'Innova' },
  { id: 'innova-condor', name: 'Condor', brand: 'Innova' },
  { id: 'innova-croc', name: 'Croc', brand: 'Innova' },
  { id: 'innova-hawg', name: 'Hawg', brand: 'Innova' },
  { id: 'innova-hydra', name: 'Hydra', brand: 'Innova' },
  { id: 'innova-juggernaut', name: 'Juggernaut', brand: 'Innova' },
  { id: 'innova-monster', name: 'Monster', brand: 'Innova' },
  { id: 'innova-power-disc', name: 'Power Disc', brand: 'Innova' },
  { id: 'innova-power-disc-2', name: 'Power Disc 2', brand: 'Innova' },
  { id: 'innova-sonic', name: 'Sonic', brand: 'Innova' },
  { id: 'innova-vulcan', name: 'Vulcan', brand: 'Innova' },
  { id: 'innova-wahoo', name: 'Wahoo', brand: 'Innova' },
  { id: 'kastaplast-lva', name: 'Älva', brand: 'Kastaplast' },
  { id: 'kastaplast-guld', name: 'Guld', brand: 'Kastaplast' },
  { id: 'kastaplast-hydrogen', name: 'Hydrogen', brand: 'Kastaplast' },
  { id: 'kastaplast-idog', name: 'Idog', brand: 'Kastaplast' },
  { id: 'kastaplast-impa', name: 'Impa', brand: 'Kastaplast' },
  { id: 'kastaplast-jrn', name: 'Järn', brand: 'Kastaplast' },
  { id: 'kastaplast-kaxe', name: 'Kaxe', brand: 'Kastaplast' },
  { id: 'kastaplast-kaxe-z', name: 'Kaxe Z', brand: 'Kastaplast' },
  { id: 'kastaplast-krut', name: 'Krut', brand: 'Kastaplast' },
  { id: 'kastaplast-malm', name: 'Malm', brand: 'Kastaplast' },
  { id: 'kastaplast-neon', name: 'Neon', brand: 'Kastaplast' },
  { id: 'kastaplast-nord', name: 'Nord', brand: 'Kastaplast' },
  { id: 'kastaplast-reko', name: 'Reko', brand: 'Kastaplast' },
  { id: 'kastaplast-reko-x', name: 'Reko X', brand: 'Kastaplast' },
  { id: 'kastaplast-silicon', name: 'Silicon', brand: 'Kastaplast' },
  { id: 'kastaplast-skylark', name: 'Skylark', brand: 'Kastaplast' },
  { id: 'kastaplast-sparrow', name: 'Sparrow', brand: 'Kastaplast' },
  { id: 'kastaplast-sten', name: 'Sten', brand: 'Kastaplast' },
  { id: 'kastaplast-stig', name: 'Stig', brand: 'Kastaplast' },
  { id: 'kastaplast-stl', name: 'Stål', brand: 'Kastaplast' },
  { id: 'kastaplast-svea', name: 'Svea', brand: 'Kastaplast' },
  { id: 'kastaplast-titanium', name: 'Titanium', brand: 'Kastaplast' },
  { id: 'kastaplast-tuff', name: 'Tuff', brand: 'Kastaplast' },
  { id: 'kastaplast-vass', name: 'Vass', brand: 'Kastaplast' },
  { id: 'kastaplast-xenon', name: 'Xenon', brand: 'Kastaplast' },
  { id: 'kastaplast-frid', name: 'Frid', brand: 'Kastaplast' },
  { id: 'kastaplast-sled', name: 'Sled', brand: 'Kastaplast' },
  { id: 'latitude-ballista', name: 'Ballista', brand: 'Latitude 64' },
  { id: 'latitude-bite', name: 'Bite', brand: 'Latitude 64' },
  { id: 'latitude-bolt', name: 'Bolt', brand: 'Latitude 64' },
  { id: 'latitude-brave', name: 'Brave', brand: 'Latitude 64' },
  { id: 'latitude-compass', name: 'Compass', brand: 'Latitude 64' },
  { id: 'latitude-core', name: 'Core', brand: 'Latitude 64' },
  { id: 'latitude-essence', name: 'Essence', brand: 'Latitude 64' },
  { id: 'latitude-founder', name: 'Founder', brand: 'Latitude 64' },
  { id: 'latitude-function', name: 'Function', brand: 'Latitude 64' },
  { id: 'latitude-fury', name: 'Fury', brand: 'Latitude 64' },
  { id: 'latitude-gladiator', name: 'Gladiator', brand: 'Latitude 64' },
  { id: 'latitude-glory', name: 'Glory', brand: 'Latitude 64' },
  { id: 'latitude-havoc', name: 'Havoc', brand: 'Latitude 64' },
  { id: 'latitude-honor', name: 'Honor', brand: 'Latitude 64' },
  { id: 'latitude-hope', name: 'Hope', brand: 'Latitude 64' },
  { id: 'latitude-instinct', name: 'Instinct', brand: 'Latitude 64' },
  { id: 'latitude-maul', name: 'Maul', brand: 'Latitude 64' },
  { id: 'latitude-mercy', name: 'Mercy', brand: 'Latitude 64' },
  { id: 'latitude-method', name: 'Method', brand: 'Latitude 64' },
  { id: 'latitude-musket', name: 'Musket', brand: 'Latitude 64' },
  { id: 'latitude-mutant', name: 'Mutant', brand: 'Latitude 64' },
  { id: 'latitude-origin', name: 'Origin', brand: 'Latitude 64' },
  { id: 'latitude-paradigm', name: 'Paradigm', brand: 'Latitude 64' },
  { id: 'latitude-peak', name: 'Peak', brand: 'Latitude 64' },
  { id: 'latitude-pearl', name: 'Pearl', brand: 'Latitude 64' },
  { id: 'latitude-pioneer', name: 'Pioneer', brand: 'Latitude 64' },
  { id: 'latitude-pure', name: 'Pure', brand: 'Latitude 64' },
  { id: 'latitude-recoil', name: 'Recoil', brand: 'Latitude 64' },
  { id: 'latitude-rive', name: 'Rive', brand: 'Latitude 64' },
  { id: 'latitude-ruby', name: 'Ruby', brand: 'Latitude 64' },
  { id: 'latitude-savior', name: 'Savior', brand: 'Latitude 64' },
  { id: 'latitude-scythe', name: 'Scythe', brand: 'Latitude 64' },
  { id: 'latitude-sinus', name: 'Sinus', brand: 'Latitude 64' },
  { id: 'latitude-spark', name: 'Spark', brand: 'Latitude 64' },
  { id: 'latitude-splice', name: 'Splice', brand: 'Latitude 64' },
  { id: 'latitude-spore', name: 'Spore', brand: 'Latitude 64' },
  { id: 'latitude-stiletto', name: 'Stiletto', brand: 'Latitude 64' },
  { id: 'latitude-strive', name: 'Strive', brand: 'Latitude 64' },
  { id: 'latitude-sweep', name: 'Sweep', brand: 'Latitude 64' },
  { id: 'latitude-trident', name: 'Trident', brand: 'Latitude 64' },
  { id: 'latitude-vision', name: 'Vision', brand: 'Latitude 64' },
  { id: 'latitude-hunter', name: 'Hunter', brand: 'Latitude 64' },
  { id: 'latitude-clozer', name: 'Clozer', brand: 'Latitude 64' },
  { id: 'latitude-clutch', name: 'Clutch', brand: 'Latitude 64' },
  { id: 'latitude-prowler', name: 'Prowler', brand: 'Latitude 64' },
  { id: 'latitude-enemy', name: 'Enemy', brand: 'Latitude 64' },
  { id: 'latitude-fighter', name: 'Fighter', brand: 'Latitude 64' },
  { id: 'latitude-cannon', name: 'Cannon', brand: 'Latitude 64' },
  { id: 'latitude-rival', name: 'Rival', brand: 'Latitude 64' },
  { id: 'latitude-baron', name: 'Baron', brand: 'Latitude 64' },
  { id: 'latitude-code', name: 'Code', brand: 'Latitude 64' },
  { id: 'latitude-code-x', name: 'Code-X', brand: 'Latitude 64' },
  { id: 'latitude-duchess', name: 'Duchess', brand: 'Latitude 64' },
  { id: 'latitude-lander', name: 'Lander', brand: 'Latitude 64' },
  { id: 'latitude-beetle', name: 'Beetle', brand: 'Latitude 64' },
  { id: 'latitude-culverin', name: 'Culverin', brand: 'Latitude 64' },
  { id: 'latitude-gatekeeper', name: 'Gatekeeper', brand: 'Latitude 64' },
  { id: 'latitude-knight', name: 'Knight', brand: 'Latitude 64' },
  { id: 'latitude-macana', name: 'Macana', brand: 'Latitude 64' },
  { id: 'latitude-northman', name: 'Northman', brand: 'Latitude 64' },
  { id: 'latitude-spike', name: 'Spike', brand: 'Latitude 64' },
  { id: 'latitude-striker', name: 'Striker', brand: 'Latitude 64' },
  { id: 'latitude-xxx', name: 'XXX', brand: 'Latitude 64' },
  { id: 'millennium-jls', name: 'JLS', brand: 'Millennium' },
  { id: 'millennium-orion-lf', name: 'Orion LF', brand: 'Millennium' },
  { id: 'millennium-polaris-ls', name: 'Polaris LS', brand: 'Millennium' },
  { id: 'mvp-anode', name: 'Anode', brand: 'MVP' },
  { id: 'mvp-ascend', name: 'Ascend', brand: 'MVP' },
  { id: 'mvp-balance', name: 'Balance', brand: 'MVP' },
  { id: 'mvp-catalyst', name: 'Catalyst', brand: 'MVP' },
  { id: 'mvp-deflector', name: 'Deflector', brand: 'MVP' },
  { id: 'mvp-delirium', name: 'Delirium', brand: 'MVP' },
  { id: 'mvp-detour', name: 'Detour', brand: 'MVP' },
  { id: 'mvp-dimension', name: 'Dimension', brand: 'MVP' },
  { id: 'mvp-drift', name: 'Drift', brand: 'MVP' },
  { id: 'mvp-echo', name: 'Echo', brand: 'MVP' },
  { id: 'mvp-energy', name: 'Energy', brand: 'MVP' },
  { id: 'mvp-engine', name: 'Engine', brand: 'MVP' },
  { id: 'mvp-entropy', name: 'Entropy', brand: 'MVP' },
  { id: 'mvp-excite', name: 'Excite', brand: 'MVP' },
  { id: 'mvp-fireball', name: 'Fireball', brand: 'MVP' },
  { id: 'mvp-flare', name: 'Flare', brand: 'MVP' },
  { id: 'mvp-glitch', name: 'Glitch', brand: 'MVP' },
  { id: 'rpm-huia', name: 'Huia', brand: 'RPM Discs' },
  { id: 'mvp-impulse', name: 'Impulse', brand: 'MVP' },
  { id: 'mvp-inertia', name: 'Inertia', brand: 'MVP' },
  { id: 'mvp-ion', name: 'Ion', brand: 'MVP' },
  { id: 'mvp-jet', name: 'Jet', brand: 'MVP' },
  { id: 'rpm-kahu', name: 'Kahu', brand: 'RPM Discs' },
  { id: 'rpm-kea', name: 'Kea', brand: 'RPM Discs' },
  { id: 'rpm-kiwi', name: 'Kiwi', brand: 'RPM Discs' },
  { id: 'rpm-kotare', name: 'Kotare', brand: 'RPM Discs' },
  { id: 'mvp-lift', name: 'Lift', brand: 'MVP' },
  { id: 'mvp-matrix', name: 'Matrix', brand: 'MVP' },
  { id: 'mvp-mayhem', name: 'Mayhem', brand: 'MVP' },
  { id: 'mvp-motion', name: 'Motion', brand: 'MVP' },
  { id: 'mvp-nitro', name: 'Nitro', brand: 'MVP' },
  { id: 'mvp-nomad', name: 'Nomad', brand: 'MVP' },
  { id: 'mvp-ohm', name: 'Ohm', brand: 'MVP' },
  { id: 'mvp-orbital', name: 'Orbital', brand: 'MVP' },
  { id: 'mvp-panic', name: 'Panic', brand: 'MVP' },
  { id: 'mvp-paradox', name: 'Paradox', brand: 'MVP' },
  { id: 'mvp-phase', name: 'Phase', brand: 'MVP' },
  { id: 'mvp-photon', name: 'Photon', brand: 'MVP' },
  { id: 'mvp-pilot', name: 'Pilot', brand: 'MVP' },
  { id: 'mvp-pitch', name: 'Pitch', brand: 'MVP' },
  { id: 'mvp-pixel', name: 'Pixel', brand: 'MVP' },
  { id: 'mvp-range', name: 'Range', brand: 'MVP' },
  { id: 'mvp-reactor', name: 'Reactor', brand: 'MVP' },
  { id: 'mvp-relativity', name: 'Relativity', brand: 'MVP' },
  { id: 'mvp-resistor', name: 'Resistor', brand: 'MVP' },
  { id: 'mvp-runway', name: 'Runway', brand: 'MVP' },
  { id: 'rpm-ruru', name: 'Ruru', brand: 'RPM Discs' },
  { id: 'mvp-shift', name: 'Shift', brand: 'MVP' },
  { id: 'mvp-signal', name: 'Signal', brand: 'MVP' },
  { id: 'mvp-spin', name: 'Spin', brand: 'MVP' },
  { id: 'mvp-stabilizer', name: 'Stabilizer', brand: 'MVP' },
  { id: 'mvp-tantrum', name: 'Tantrum', brand: 'MVP' },
  { id: 'mvp-teleport', name: 'Teleport', brand: 'MVP' },
  { id: 'mvp-tempo', name: 'Tempo', brand: 'MVP' },
  { id: 'mvp-tenacity', name: 'Tenacity', brand: 'MVP' },
  { id: 'mvp-terra', name: 'Terra', brand: 'MVP' },
  { id: 'mvp-time-lapse', name: 'Time-Lapse', brand: 'MVP' },
  { id: 'mvp-trace', name: 'Trace', brand: 'MVP' },
  { id: 'mvp-trail', name: 'Trail', brand: 'MVP' },
  { id: 'mvp-turbulence', name: 'Turbulence', brand: 'MVP' },
  { id: 'mvp-uplink', name: 'Uplink', brand: 'MVP' },
  { id: 'mvp-vanish', name: 'Vanish', brand: 'MVP' },
  { id: 'mvp-virus', name: 'Virus', brand: 'MVP' },
  { id: 'mvp-watt', name: 'Watt', brand: 'MVP' },
  { id: 'mvp-wave', name: 'Wave', brand: 'MVP' },
  { id: 'mvp-wrath', name: 'Wrath', brand: 'MVP' },
  { id: 'mvp-zenith', name: 'Zenith', brand: 'MVP' },
  { id: 'prodigy-archive', name: 'Archive', brand: 'Prodigy' },
  { id: 'prodigy-distortion', name: 'Distortion', brand: 'Prodigy' },
  { id: 'prodigy-fx-2', name: 'FX-2', brand: 'Prodigy' },
  { id: 'prodigy-fx-3', name: 'FX-3', brand: 'Prodigy' },
  { id: 'prodigy-fx-4', name: 'FX-4', brand: 'Prodigy' },
  { id: 'prodigy-feedback', name: 'Feedback', brand: 'Prodigy' },
  { id: 'prodigy-h3', name: 'H3', brand: 'Prodigy' },
  { id: 'prodigy-h3v2', name: 'H3V2', brand: 'Prodigy' },
  { id: 'prodigy-h4', name: 'H4', brand: 'Prodigy' },
  { id: 'prodigy-h4v2', name: 'H4V2', brand: 'Prodigy' },
  { id: 'prodigy-h5', name: 'H5', brand: 'Prodigy' },
  { id: 'prodigy-h7', name: 'H7', brand: 'Prodigy' },
  { id: 'prodigy-mx-1', name: 'MX-1', brand: 'Prodigy' },
  { id: 'prodigy-mx-2', name: 'MX-2', brand: 'Prodigy' },
  { id: 'prodigy-mx-3', name: 'MX-3', brand: 'Prodigy' },
  { id: 'prodigy-px-3', name: 'PX-3', brand: 'Prodigy' },
  { id: 'prodigy-reverb', name: 'Reverb', brand: 'Prodigy' },
  { id: 'prodigy-shadowfax', name: 'Shadowfax', brand: 'Prodigy' },
  { id: 'prodigy-stryder', name: 'Stryder', brand: 'Prodigy' },
  { id: 'prodigy-x3', name: 'X3', brand: 'Prodigy' },
  { id: 'viking-avalanche', name: 'Avalanche', brand: 'Viking Discs' },
  { id: 'viking-hurricane', name: 'Hurricane', brand: 'Viking Discs' },
  { id: 'viking-pipeline', name: 'Pipeline', brand: 'Viking Discs' },
  { id: 'viking-quake', name: 'Quake', brand: 'Viking Discs' },
  { id: 'viking-rogue', name: 'Rogue', brand: 'Viking Discs' },
  { id: 'viking-squall', name: 'Squall', brand: 'Viking Discs' },
  { id: 'westside-adder', name: 'Adder', brand: 'Westside Discs' },
  { id: 'westside-bear', name: 'Bear', brand: 'Westside Discs' },
  { id: 'westside-boatman', name: 'Boatman', brand: 'Westside Discs' },
  { id: 'westside-crown', name: 'Crown', brand: 'Westside Discs' },
  { id: 'westside-destiny', name: 'Destiny', brand: 'Westside Discs' },
  { id: 'westside-fortress', name: 'Fortress', brand: 'Westside Discs' },
  { id: 'westside-giant', name: 'Giant', brand: 'Westside Discs' },
  { id: 'westside-king', name: 'King', brand: 'Westside Discs' },
  { id: 'westside-maiden', name: 'Maiden', brand: 'Westside Discs' },
  { id: 'westside-prince', name: 'Prince', brand: 'Westside Discs' },
  { id: 'westside-shield', name: 'Shield', brand: 'Westside Discs' },
  { id: 'westside-swan-2', name: 'Swan 2', brand: 'Westside Discs' },
  { id: 'westside-tide', name: 'Tide', brand: 'Westside Discs' },
  { id: 'westside-underworld', name: 'Underworld', brand: 'Westside Discs' },
  { id: 'westside-world', name: 'World', brand: 'Westside Discs' },
  { id: 'westside-the-count', name: 'The Count', brand: 'Westside Discs' },
  { id: 'axiom-eclipse-vanity', name: 'Eclipse Vanity', brand: 'Axiom' },
  { id: 'discmania-meta-dagger', name: 'Meta Dagger', brand: 'Discmania' },
  // RPM Discs (additional)
  { id: 'rpm-tui', name: 'Tui', brand: 'RPM Discs' },
  { id: 'rpm-weka', name: 'Weka', brand: 'RPM Discs' },
  { id: 'rpm-aotearoa', name: 'Aotearoa', brand: 'RPM Discs' },
  { id: 'rpm-kotuku', name: 'Kotuku', brand: 'RPM Discs' },
  { id: 'rpm-takapu', name: 'Takapu', brand: 'RPM Discs' },
  { id: 'rpm-taipan', name: 'Taipan', brand: 'RPM Discs' },
  { id: 'rpm-destiny', name: 'Destiny', brand: 'RPM Discs' },
  // ── Added from audit ──────────────────────────────────────────────────────
  // List 2: missing disc models (2+ appearances in unmatched)
  { id: 'mvp-trance', name: 'Trance', brand: 'MVP' },
  { id: 'innova-xero', name: 'Xero', brand: 'Innova' },
  { id: 'innova-whale', name: 'Whale', brand: 'Innova' },
  { id: 'latitude-dagger', name: 'Dagger', brand: 'Latitude 64' },
  { id: 'discmania-drop', name: 'Drop', brand: 'Discmania' },
  { id: 'tsa-synapse', name: 'Synapse', brand: 'Thought Space Athletics' },
  { id: 'gateway-phi', name: 'Phi', brand: 'Gateway' },
  { id: 'gateway-penrose', name: 'Penrose', brand: 'Gateway' },
  { id: 'latitude-faith', name: 'Faith', brand: 'Latitude 64' },
  { id: 'innova-polecat', name: 'Polecat', brand: 'Innova' },
  { id: 'innova-skeeter', name: 'Skeeter', brand: 'Innova' },
  { id: 'innova-manta', name: 'Manta', brand: 'Innova' },
  { id: 'innova-dragon', name: 'Dragon', brand: 'Innova' },
  { id: 'innova-zephyr', name: 'Zephyr', brand: 'Innova' },
  { id: 'prodigy-omega', name: 'Omega', brand: 'Prodigy' },
  // Thought Space Athletics
  { id: 'tsa-muse', name: 'Muse', brand: 'Thought Space Athletics' },
  { id: 'tsa-temple', name: 'Temple', brand: 'Thought Space Athletics' },
  { id: 'tsa-construct', name: 'Construct', brand: 'Thought Space Athletics' },
  { id: 'tsa-mantra', name: 'Mantra', brand: 'Thought Space Athletics' },
  { id: 'tsa-pathfinder', name: 'Pathfinder', brand: 'Thought Space Athletics' },
  { id: 'tsa-praxis', name: 'Praxis', brand: 'Thought Space Athletics' },
  { id: 'tsa-votum', name: 'Votum', brand: 'Thought Space Athletics' },
  { id: 'tsa-animus', name: 'Animus', brand: 'Thought Space Athletics' },
  // Gateway Disc Sports
  // (Phi and Penrose already added above)
  // Lone Star Discs
  { id: 'lone-star-artemis', name: 'Artemis', brand: 'Lone Star Discs' },
  { id: 'lone-star-tombstone', name: 'Tombstone', brand: 'Lone Star Discs' },
  { id: 'lone-star-spur', name: 'Spur', brand: 'Lone Star Discs' },
  { id: 'lone-star-middy', name: 'Middy', brand: 'Lone Star Discs' },
  { id: 'lone-star-bayonet', name: 'Bayonet', brand: 'Lone Star Discs' },
  { id: 'lone-star-nimitz', name: 'Nimitz', brand: 'Lone Star Discs' },
  { id: 'lone-star-crockett', name: 'Crockett', brand: 'Lone Star Discs' },
  { id: 'lone-star-bowie', name: 'Bowie', brand: 'Lone Star Discs' },
  { id: 'lone-star-seguin', name: 'Seguin', brand: 'Lone Star Discs' },
  { id: 'lone-star-warbird', name: 'Warbird', brand: 'Lone Star Discs' },
  { id: 'lone-star-curl', name: 'Curl', brand: 'Lone Star Discs' },
  { id: 'lone-star-harpoon', name: 'Harpoon', brand: 'Lone Star Discs' },
  { id: 'lone-star-walker', name: 'Walker', brand: 'Lone Star Discs' },
  { id: 'lone-star-chupacabra', name: 'Chupacabra', brand: 'Lone Star Discs' },
  { id: 'lone-star-texas-ranger', name: 'Texas Ranger', brand: 'Lone Star Discs' },
  // Clash Discs
  { id: 'clash-popcorn', name: 'Popcorn', brand: 'Clash Discs' },
  { id: 'clash-salt', name: 'Salt', brand: 'Clash Discs' },
  { id: 'clash-marvel', name: 'Marvel', brand: 'Clash Discs' },
  { id: 'clash-canyon', name: 'Canyon', brand: 'Clash Discs' },
  { id: 'clash-reach', name: 'Reach', brand: 'Clash Discs' },
  { id: 'clash-weapon', name: 'Weapon', brand: 'Clash Discs' },
  // EggShell Discs
  { id: 'eggshell-rex', name: 'Rex', brand: 'EggShell Discs' },
  { id: 'eggshell-triceratops', name: 'Triceratops', brand: 'EggShell Discs' },
  { id: 'eggshell-stegosaurus', name: 'Stegosaurus', brand: 'EggShell Discs' },
  { id: 'eggshell-brachiosaurus', name: 'Brachiosaurus', brand: 'EggShell Discs' },
  { id: 'eggshell-pterodactyl', name: 'Pterodactyl', brand: 'EggShell Discs' },
  // Prodiscus
  { id: 'prodiscus-launcher-os', name: 'Launcher OS', brand: 'Prodiscus' },
  { id: 'prodiscus-spy', name: 'Spy', brand: 'Prodiscus' },
  { id: 'prodiscus-skyway', name: 'Skyway', brand: 'Prodiscus' },
  { id: 'prodiscus-belleair', name: 'Belleair', brand: 'Prodiscus' },
  // Westside new putters
  { id: 'westside-magic', name: 'Magic', brand: 'Westside Discs' },
  { id: 'westside-voodoo', name: 'Voodoo', brand: 'Westside Discs' },
  { id: 'westside-ahti', name: 'Ahti', brand: 'Westside Discs' },
  { id: 'westside-anvil', name: 'Anvil', brand: 'Westside Discs' },
  { id: 'westside-bard', name: 'Bard', brand: 'Westside Discs' },
  { id: 'westside-longbowman', name: 'Longbowman', brand: 'Westside Discs' },
  { id: 'westside-queen', name: 'Queen', brand: 'Westside Discs' },
  { id: 'westside-seer', name: 'Seer', brand: 'Westside Discs' },
  { id: 'westside-sorcerer', name: 'Sorcerer', brand: 'Westside Discs' },
  { id: 'westside-war-horse', name: 'War Horse', brand: 'Westside Discs' },
  // Discraft additions
  { id: 'discraft-archer', name: 'Archer', brand: 'Discraft' },
  { id: 'discraft-avenger', name: 'Avenger', brand: 'Discraft' },
  { id: 'discraft-pulse', name: 'Pulse', brand: 'Discraft' },
  { id: 'discraft-rattler', name: 'Rattler', brand: 'Discraft' },
  { id: 'discraft-ringer', name: 'Ringer', brand: 'Discraft' },
  { id: 'discraft-xs', name: 'XS', brand: 'Discraft' },
  { id: 'discraft-zeppelin', name: 'Zeppelin', brand: 'Discraft' },
  // Axiom additions
  { id: 'axiom-coalesce', name: 'Coalesce', brand: 'Axiom' },
  { id: 'axiom-crux', name: 'Crux', brand: 'Axiom' },
  { id: 'axiom-mana', name: 'Mana', brand: 'Axiom' },
  { id: 'axiom-omen', name: 'Omen', brand: 'Axiom' },
  // MVP additions
  { id: 'mvp-alter', name: 'Alter', brand: 'MVP' },
  { id: 'mvp-particle', name: 'Particle', brand: 'MVP' },
  { id: 'mvp-pneuma', name: 'Pneuma', brand: 'MVP' },
  // Prodigy additions
  { id: 'prodigy-a5', name: 'A5', brand: 'Prodigy' },
  { id: 'prodigy-d6', name: 'D6', brand: 'Prodigy' },
  { id: 'prodigy-f2', name: 'F2', brand: 'Prodigy' },
  { id: 'prodigy-f7', name: 'F7', brand: 'Prodigy' },
  { id: 'prodigy-f9', name: 'F9', brand: 'Prodigy' },
  { id: 'prodigy-falcor', name: 'Falcor', brand: 'Prodigy' },
  { id: 'prodigy-pa-3', name: 'PA-3', brand: 'Prodigy' },
  { id: 'prodigy-pa-5', name: 'PA-5', brand: 'Prodigy' },
  { id: 'prodigy-x4', name: 'X4', brand: 'Prodigy' },
  { id: 'prodigy-x5', name: 'X5', brand: 'Prodigy' },
  // Streamline additions
  { id: 'streamline-parachute', name: 'Parachute', brand: 'Streamline' },
  // Discmania additions
  { id: 'discmania-fisken', name: 'Fisken', brand: 'Discmania' },
];

// ── Store configs ─────────────────────────────────────────────────────────────
// Category slugs that indicate used/second-hand products — applied universally
// In WooCommerce HTML: appears as "product_cat-{slug}" in the <li> class
// In WooCommerce REST API: appears in product.categories[].slug
const SKIP_CATEGORY_SLUGS = ['second-hand', 'brukt', 'used', 'nice-not-perfect'];

// Used keyword check for Shopify product_type / tags fields
function isUsedProductMeta(productType, tags) {
  const haystack = [productType || '', ...(tags || [])].join(' ').toLowerCase();
  return ['second hand', 'second-hand', 'brukt', 'used', 'nice not perfect', 'b-grade'].some((kw) => haystack.includes(kw));
}

const STORE_CONFIGS = {
  golfdiscer: {
    key: 'golfdiscer',
    name: 'GolfDiscer',
    baseUrl: 'https://golfdiscer.no',
    freeShippingOver: 799,
    shipping: 45,
    categoryUrls: [
      'https://golfdiscer.no/product-category/discer/',
    ],
    skipCategorySlugs: SKIP_CATEGORY_SLUGS,
  },
  frisbeesor: {
    key: 'frisbeesor',
    name: 'Frisbee Sør',
    baseUrl: 'https://frisbeesor.no',
    freeShippingOver: 699,
    shipping: 45,
    categoryUrls: [
      'https://frisbeesor.no/product-category/discer/',
    ],
    skipCategorySlugs: SKIP_CATEGORY_SLUGS,
  },
  discexpress: {
    key: 'discexpress',
    name: 'Discexpress',
    url: 'https://www.discexpress.se',
    country: 'SE',
    currency: 'SEK',
    shipping: 41,
    voec: true,
  },
  rocketdiscs: {
    key: 'rocketdiscs',
    name: 'Rocketdiscs',
    url: 'https://rocketdiscs.com',
    country: 'SE',
    currency: 'EUR',
    shipping: 67,
    voec: true,
  },
};

// ── Variant extraction (delegates to plastic-types.js) ───────────────────────

/** Extract plastic type and edition from a raw product name */
function extractVariant(rawName, brand) {
  const { plastic, edition } = parseProductName(rawName, brand);
  return { plastic, edition };
}

// ── Shared helpers ────────────────────────────────────────────────────────────

/** Normalise a string for comparison */
function norm(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

const NON_DISC_KEYWORDS = [
  'bag', 'sekk', 'ryggsekk', 'basket', 'kurv', 'armbånd', 'handledds',
  'towel', 'håndkle', 'marker', 'kasse', 'mold',
  // Accessories — added from scrape audit
  'rainfly', 'slim rainfly', 'backpack', 'flashlight', 'stool',
  'flaske', 'klut', 'paraply', 'genser', 'jersey', 'hoodie',
  'gloves', 'warmers', 'patch', 'gavekort', 'startsett', 'zipchip',
  'retriever', 'sound barrier', 'probasket', 'traveler', 'target',
  'led', 'kurvlys', 'disc doctor', 'mikrofiber', 'pins', 'bagtag',
  'claw', 'chalk bag', 'tripod', 'thro', 'dry bag', 'lens cap',
  'mini metal', 'pvc', 'forcefield', 'frame', 'station',
];

/** Returns false if the product name contains a non-disc keyword */
function isDiscProduct(rawName) {
  const lower = rawName.toLowerCase();
  return !NON_DISC_KEYWORDS.some(kw =>
    new RegExp('(?:^|[\\s,/])' + kw + '(?:[\\s,/]|$)').test(lower)
  );
}

/** Match a raw product name to a disc in the catalog. Longest match wins. */
function matchDisc(rawProductName) {
  if (!isDiscProduct(rawProductName)) return null;

  // Normalise: lowercase, collapse specials to spaces
  let normalised = norm(rawProductName);
  // Strip year prefix e.g. "2024 Chris Dickerson Tour Series Buzzz"
  normalised = normalised.replace(/^20\d{2}\s+/, '');
  // Insert space before digit suffix to handle "Swan2" → "swan 2", "Aviar3" → "aviar 3"
  normalised = normalised.replace(/([a-z])(\d)/g, '$1 $2');

  let bestMatch = null;
  let bestScore = 0;

  for (const disc of DISC_CATALOG) {
    let discName = norm(disc.name);
    discName = discName.replace(/([a-z])(\d)/g, '$1 $2');
    const pattern = new RegExp(
      '(?:^|\\s)' + discName.replace(/\s+/g, '\\s+') + '(?:\\s|$)',
      'i'
    );
    if (pattern.test(normalised)) {
      // Very short disc names (<= 2 chars) require the brand name to also appear.
      // Exception: Discmania line plastics (C-Line, S-Line, D-Line, P-Line) infer brand.
      if (discName.length <= 2) {
        const brandNorm = norm(disc.brand);
        const brandPattern = new RegExp('(?:^|\\s)' + brandNorm.replace(/\s+/g, '\\s+') + '(?:\\s|$)', 'i');
        const hasDiscmaniaPlastic = disc.brand === 'Discmania' &&
          /\b(?:c[- ]line|s[- ]line|d[- ]line|p[- ]line|q[- ]line)\b/i.test(normalised);
        const hasInnovaPlastic = disc.brand === 'Innova' &&
          /\b(?:champion|star|gstar|blizzard|halo|pro|xt|dx|r-pro|jstar)\b/i.test(normalised);
        if (!hasDiscmaniaPlastic && !hasInnovaPlastic && !brandPattern.test(normalised)) continue;
      }
      const score = discName.length;
      if (score > bestScore) {
        bestScore = score;
        bestMatch = disc;
      }
    }
  }

  // Log low-confidence matches (disc name is very short relative to product name)
  if (bestMatch) {
    const words = normalised.split(/\s+/).length;
    if (bestScore <= 2 || (bestScore / normalised.length) < 0.2) {
      console.log(`  [low-confidence] "${rawProductName}" → ${bestMatch.id} (nameLen=${bestScore}, productWords=${words})`);
    }
  }

  return bestMatch;
}

module.exports = { DISC_CATALOG, STORE_CONFIGS, SKIP_CATEGORY_SLUGS, norm, matchDisc, isDiscProduct, NON_DISC_KEYWORDS, extractVariant, PLASTIC_TYPES, parseProductName, isUsedDisc, isMiniDisc, isNonDiscProduct, isUsedProductMeta };
